
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  EMPLOYEE: 'EMPLOYEE',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const LeaveType = {
  FULL_DAY: 'FULL_DAY',
  HALF_DAY: 'HALF_DAY'
} as const

export type LeaveType = (typeof LeaveType)[keyof typeof LeaveType]


export const LeaveStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const

export type LeaveStatus = (typeof LeaveStatus)[keyof typeof LeaveStatus]


export const TaskStatus = {
  OPEN: 'OPEN',
  COMPLETED: 'COMPLETED'
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]
